"""prva migracija

Revision ID: 06756b5c65ed
Revises: 
Create Date: 2026-05-14 12:39:07.687546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06756b5c65ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=100), nullable=False),
    sa.Column('drzava', sa.String(length=100), nullable=False),
    sa.Column('grad', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('cijena', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klijenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=100), nullable=False),
    sa.Column('prezime', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefon', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('zaposlenici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=100), nullable=False),
    sa.Column('prezime', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pozicija', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rezervacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('klijent_id', sa.Integer(), nullable=False),
    sa.Column('destinacija_id', sa.Integer(), nullable=False),
    sa.Column('datum_rezervacije', sa.Date(), nullable=False),
    sa.Column('broj_osoba', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['destinacija_id'], ['destinacije.id'], ),
    sa.ForeignKeyConstraint(['klijent_id'], ['klijenti.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rezervacije')
    op.drop_table('zaposlenici')
    op.drop_table('klijenti')
    op.drop_table('destinacije')
    # ### end Alembic commands ###
